---
driver_plugin: vagrant

provisioner:
  name: chef_solo

platforms:
- name: centos
  driver:
    box: learningchef/centos65
    box_url: learningchef/centos65

suites:
  - name: default
    run_list:
    attributes:
